name: memescraper
description: MemeScraper is a non-official API of [Know Your Meme](https://knowyourmeme.com/) made using scraping.
version: 1.0.1
homepage: https://github.com/KikiManjaro/MemeScraper

environment:
  sdk: '>=2.10.0 <3.0.0'
dev_dependencies:
  pedantic: ^1.9.0
dependencies:
  web_scraper: ^0.1.4
